import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="sticky top-0 z-50 w-full bg-white/80 backdrop-blur-md border-b border-gray-100">
          <div className="mx-auto w-full max-w-screen-xl px-4 h-16 flex items-center justify-between">
            {/* Logo */}
            <Link href="/" className="flex items-center space-x-2">
              <span className="text-xl font-bold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                TechBuilt
              </span>
            </Link>

            {/* Nav Menu */}
            <nav className="hidden md:flex items-center space-x-6 text-sm font-medium text-gray-600">
              <Link href="/" className="hover:text-blue-600 transition-colors">
                Home
              </Link>
              <Link
                href="/about"
                className="hover:text-blue-600 transition-colors"
              >
                About
              </Link>
              <Link
                href="/services"
                className="hover:text-blue-600 transition-colors"
              >
                Services
              </Link>
              <Link
                href="/contact"
                className="hover:text-blue-600 transition-colors"
              >
                Contact
              </Link>
            </nav>

            {/* Action Button */}
            <div className="flex items-center space-x-4">
              <button className="hidden sm:inline-flex text-sm font-medium text-gray-600 hover:text-blue-600 transition-colors">
                Sign In
              </button>
              <button className="inline-flex items-center justify-center px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors">
                Get Started
              </button>
            </div>
          </div>
        </header>
        {children}
        <footer className="w-full bg-gray-50 border-t border-gray-100 mt-auto">
          <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8 px-4">
            <div className="md:flex md:justify-between">
              {/* Logo */}
              <div className="mb-6 md:mb-0">
                <Link href="/" className="flex items-center mb-3">
                  <span className="text-xl font-bold text-gray-900">
                    TechBuilt
                  </span>
                </Link>
                <p className="text-sm text-gray-500 max-w-xs">
                  Your best platform to show your potential.
                </p>
              </div>

              {/* Link */}
              <div className="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
                <div>
                  <h2 className="mb-4 text-sm font-semibold text-gray-900 uppercase tracking-wider">
                    Follow us
                  </h2>
                  <ul className="text-gray-600 text-sm space-y-2">
                    <li>
                      <Link
                        href="https://github.com"
                        className="hover:underline"
                      >
                        Github
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="https://discord.com"
                        className="hover:underline"
                      >
                        Discord
                      </Link>
                    </li>
                  </ul>
                </div>
                <div>
                  <h2 className="mb-4 text-sm font-semibold text-gray-900 uppercase tracking-wider">
                    Legal
                  </h2>
                  <ul className="text-gray-600 text-sm space-y-2">
                    <li>
                      <Link href="/privacy" className="hover:underline">
                        Privacy Policy
                      </Link>
                    </li>
                    <li>
                      <Link href="/terms" className="hover:underline">
                        Terms &amp; Conditions
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <hr className="my-6 border-gray-200 lg:my-8" />

            {/* Copyright */}
            <div className="sm:flex sm:items-center sm:justify-between">
              <span className="text-sm text-gray-500 sm:text-center">
                © 2026{" "}
                <Link href="/" className="hover:underline">
                  TechBuilt™
                </Link>
                . All Rights Reserved.
              </span>
              <div className="flex mt-4 sm:justify-center sm:mt-0 space-x-5 text-gray-400">
                <Link
                  href="#"
                  className="hover:text-gray-900 transition-colors"
                >
                  Facebook
                </Link>
                <Link
                  href="#"
                  className="hover:text-gray-900 transition-colors"
                >
                  Twitter
                </Link>
                <Link
                  href="#"
                  className="hover:text-gray-900 transition-colors"
                >
                  GitHub
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
